In [1]:
import pandas as pd
import requests

In [25]:
inc_df = pd.read_csv('data/Texas_Incarcerated.csv') # Pulling in the incarcerated data csv and turning into a pandas dataframe

In [26]:
inc_df

,SID Number,TDCJ Number,Name,Current Facility,Gender,Race,Age,Projected Release,Maximum Sentence Date,Parole Eligibility Date,Case Number,County,Offense Code,TDCJ Offense,Sentence Date,Offense Date,Sentence (Years),Last Parole Decision,Next Parole Review Date,Parole Review Status
0,24323,2516442,"YOUNGBLOOD,GENE ODIE",Polunsky,M,W,51,12/21/7550,12/21/7550,12/21/2025,CF-95-42,Walker,9990026,MURDER - ICC OK OOC#024323,12/22/1995,08/16/1995,5555.0,NaN,12/21/2025,IN PAROLE REVIEW PROCESS
1,671628,2394062,"ONOFRE,JESSE TINAJERO",Estelle,M,H,90,04/23/2026,04/23/2026,04/22/2024,2019CR4680,Bexar,36010001,INDEC W/CHILD CONTACT,05/16/2022,08/02/2016,4.0,Denied on 06/11/2024,NaN,NOT IN REVIEW PROCESS
2,686567,311644,"PALACIOS,ROBERT LEONARD",Beto,M,H,87,09/12/2028,05/12/2036,04/15/2022,320670,Harris,22100000,BURG HAB W/I SEXUAL ABUSE,10/21/1980,01/28/1980,30.0,Denied on 05/01/2023,04/2026,NOT IN REVIEW PROCESS
3,770626,449674,"FLORES,ISABEL",Jester III,M,H,88,01/01/9999,01/01/9999,09/02/2006,86CR-1234-B,Nueces,9150000,MURDER W/DEADLY WPN,04/13/1987,09/02/1986,Life,Denied on 11/20/2024,11/2027,NOT IN REVIEW PROCESS
4,771601,1491019,"MOLETT,JOHN HENRY",W Scott,M,B,83,09/01/2025,12/02/2037,12/02/2022,1144294,Harris,12990002,AGG ROBBERY W/DW,02/21/2008,12/03/2007,30.0,Approved on 01/30/2025,NaN,NOT IN REVIEW PROCESS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139205,50824342,2419840,"DUNBAR,ANTHONY JOSEPH",Wainwright,M,B,50,01/01/5555,01/01/5555,01/01/5555,29092,Walker,11990012,SEX ABUSE CHILD CONT U/14,10/20/2022,04/01/2017,LWOP,NaN,NaN,NaN
139206,50824431,2173750,"WRIGHT,LARRY LEE",Hospital Galveston,M,W,78,01/15/2043,01/15/2043,07/16/2030,CR02467,Red River,11990004,AGG SEX ASLT CHILD,01/17/2018,01/15/2016,25.0,NaN,07/16/2030,NOT IN REVIEW PROCESS
139207,50824483,2388220,"DE LA FUENTE,LUIS ANGEL MACHUC",Hightower,M,H,27,10/21/2026,10/21/2026,11/02/2022,2016-DCR-339,Cameron,35620012,POSS OF MARIHUANA,02/23/2022,01/21/2016,5.0,Denied on 05/05/2025,05/2026,NOT IN REVIEW PROCESS
139208,50824583,2514975,"TORRES,NATHANIEL",Torres,M,W,24,08/11/2029,08/11/2029,04/20/2024,56082,Burnet,13150004,AGG ASLT CAUSE SBI,04/24/2024,08/12/2023,6.0,Denied on 10/03/2024,10/2026,NOT IN REVIEW PROCESS
139209,50824641,2244367,"WILSON,PATRICK WILLIAM",C.T. Terrell,M,H,35,10/02/2025,08/22/2028,04/08/2024,16140,Palo Pinto,52030025,PROH WEAPON,01/28/2019,07/01/2016,7.0,Approved on 08/11/2025,NaN,NOT IN REVIEW PROCESS

In [27]:
inc_df = inc_df.drop('SID Number', axis = 1) # Removing identifiable information in the dataset
inc_df = inc_df.drop('TDCJ Number', axis = 1)
inc_df = inc_df.drop('Name', axis = 1)
inc_df = inc_df.drop('Case Number', axis = 1)

In [29]:
inc_df[inc_df.County == 'Harris'] # 19355 observations in Harris

,Current Facility,Gender,Race,Age,Projected Release,Maximum Sentence Date,Parole Eligibility Date,County,Offense Code,TDCJ Offense,Sentence Date,Offense Date,Sentence (Years),Last Parole Decision,Next Parole Review Date,Parole Review Status
2,Beto,M,H,87,09/12/2028,05/12/2036,04/15/2022,Harris,22100000,BURG HAB W/I SEXUAL ABUSE,10/21/1980,01/28/1980,30.0,Denied on 05/01/2023,04/2026,NOT IN REVIEW PROCESS
4,W Scott,M,B,83,09/01/2025,12/02/2037,12/02/2022,Harris,12990002,AGG ROBBERY W/DW,02/21/2008,12/03/2007,30.0,Approved on 01/30/2025,NaN,NOT IN REVIEW PROCESS
6,Cotulla,M,W,86,01/08/2068,01/08/2068,01/08/2028,Harris,9990001,MURDER,03/27/1998,12/10/1996,70.0,NaN,01/08/2028,NOT IN REVIEW PROCESS
7,Ramsey,M,B,87,01/01/9999,01/01/9999,09/04/2027,Harris,12120000,AGG ROBBERY,10/22/1976,10/18/1975,Life,NaN,09/04/2027,NOT IN REVIEW PROCESS
15,Connally,M,H,82,08/08/2028,08/08/2028,08/08/1998,Harris,11180000,AGG SEX ASLT W/DEAD WPN,03/06/1989,07/11/1988,40.0,Denied on 09/01/2016,08/2026,NOT IN REVIEW PROCESS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139189,Telford,M,B,25,04/18/2034,04/18/2034,04/17/2028,Harris,13150005,AGG ASLT W/DWPN,04/21/2022,02/27/2021,12.0,NaN,04/17/2028,NOT IN REVIEW PROCESS
139190,Bradshaw,M,H,26,02/01/2026,07/13/2026,10/05/2024,Harris,13990075,ASLT FAM/HSEHOLD MEM W/PRE,01/30/2025,07/08/2024,2.0,Approved on 06/12/2025,NaN,NOT IN REVIEW PROCESS
139192,McConnell,M,B,22,11/20/2030,11/20/2030,11/20/2025,Harris,12990002,AGG ROBBERY-DWPN,10/20/2021,11/11/2020,10.0,NaN,11/20/2025,IN PAROLE REVIEW PROCESS
139193,Ferguson,M,B,29,05/26/2051,05/26/2051,11/25/2033,Harris,12990002,AGG ROBBERY-DWPN,02/15/2018,05/15/2016,35.0,NaN,11/25/2033,NOT IN REVIEW PROCESS
139202,Wynne,M,B,31,09/04/2048,09/04/2048,09/04/2033,Harris,9990030,MURDER,02/25/2025,09/05/2018,30.0,NaN,09/04/2033,NOT IN REVIEW PROCESS

In [30]:
inc_df[inc_df.County == 'El Paso'] # 2281 observations in El Paso

,Current Facility,Gender,Race,Age,Projected Release,Maximum Sentence Date,Parole Eligibility Date,County,Offense Code,TDCJ Offense,Sentence Date,Offense Date,Sentence (Years),Last Parole Decision,Next Parole Review Date,Parole Review Status
39,Allred,M,H,80,01/01/9999,01/01/9999,01/31/1999,El Paso,11200000,ATT AGG SEX ASLT,03/25/1993,12/29/1991,Life,Denied on 03/11/2025,03/2026,NOT IN REVIEW PROCESS
316,Beto,M,H,70,04/26/2027,04/26/2027,10/25/2024,El Paso,13150005,AGG ASLT W/DWPN,02/16/2023,04/26/2022,5.0,Denied on 02/12/2025,02/2026,NOT IN REVIEW PROCESS
460,Pack,M,W,72,08/20/2053,08/20/2053,05/29/2009,El Paso,9990023,CRIM SOLICIT COMM CAPITAL MURDER,11/03/2005,08/21/2003,50.0,Denied on 08/14/2024,Unavailable at this time.,IN PAROLE REVIEW PROCESS
476,Pack,M,H,72,09/30/2045,09/30/2045,09/30/2025,El Paso,11990004,AGG SEXUAL ASLT CHILD,02/03/2006,07/23/2001,40.0,NaN,09/30/2025,IN PAROLE REVIEW PROCESS
506,Fort Stockton,M,H,78,12/01/2025,12/08/2026,12/09/2021,El Paso,11990004,AGG SEXUAL ASLT CHILD,08/09/2018,11/16/2014,10.0,Approved on 02/23/2025,NaN,NOT IN REVIEW PROCESS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139109,Daniel,M,H,23,08/03/2026,08/03/2026,11/11/2023,El Paso,48010020,EVADING ARREST DET W/VEH,02/29/2024,08/04/2023,3.0,Denied on 06/27/2025,06/2026,NOT IN REVIEW PROCESS
139110,Sanchez,M,H,23,07/16/2028,07/16/2028,01/15/2026,El Paso,12990002,AGG ROBBERY,09/26/2024,07/16/2023,5.0,NaN,01/15/2026,IN PAROLE REVIEW PROCESS
139113,Byrd,M,H,24,01/26/2026,01/26/2026,07/28/2023,El Paso,12990002,AGG ROBBERY,09/26/2022,01/26/2021,5.0,Denied on 09/26/2023,NaN,NOT IN REVIEW PROCESS
139132,Sanchez,M,H,25,05/07/2029,05/07/2029,12/03/2024,El Paso,13150004,AGG ASLT CAUSE SERIOUS BODY INJ,12/18/2024,04/22/2024,5.0,NaN,Unavailable at this time.,IN PAROLE REVIEW PROCESS
139178,Lindsey,M,B,32,12/01/2026,12/01/2026,06/01/2024,El Paso,13150005,AGG ASLT W/DEADLY WPN,04/20/2023,12/01/2021,5.0,Denied on 07/16/2025,NaN,NOT IN REVIEW PROCESS

In [32]:
inc_df[inc_df.County == 'Dallas'] # 12966 observations in Dallas

,Current Facility,Gender,Race,Age,Projected Release,Maximum Sentence Date,Parole Eligibility Date,County,Offense Code,TDCJ Offense,Sentence Date,Offense Date,Sentence (Years),Last Parole Decision,Next Parole Review Date,Parole Review Status
8,Pack,M,B,84,06/19/2030,06/19/2030,06/19/2027,Dallas,13150005,AGG ASLT DW,11/12/2024,06/19/2024,6.0,NaN,06/19/2027,NOT IN REVIEW PROCESS
18,East Texas Treatment Facility,M,W,20,11/25/2025,11/25/2025,NaN,Dallas,23990194,"THEFT PROP >=$2,500<$30K",02/25/2025,10/06/2024,3.0,NaN,NaN,NaN
28,Allred,M,B,81,01/01/9999,01/01/9999,08/01/2019,Dallas,9150000,MURDER,09/27/1996,07/18/1989,Life,Denied on 07/10/2023,07/2026,NOT IN REVIEW PROCESS
29,Pack,M,W,80,07/13/2026,12/05/2038,11/05/2018,Dallas,10100000,AGGRV KIDNAPPING,03/01/1983,11/02/1982,50.0,Denied on 09/01/2025,NaN,NOT IN REVIEW PROCESS
47,McConnell,M,H,78,08/05/2041,08/05/2041,02/04/2019,Dallas,11990004,AGG SEX ASLT CHILD U-14,12/04/1998,03/01/1996,45.0,Denied on 05/26/2025,05/2028,NOT IN REVIEW PROCESS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139121,Plane,F,B,30,07/04/2026,07/04/2026,05/23/2026,Dallas,13990082,ASLT PEACE OFFICER/JUDGE,12/16/2024,07/04/2024,2.0,NaN,05/23/2026,NOT IN REVIEW PROCESS
139164,Bradshaw,M,B,44,01/17/2033,01/17/2033,07/18/2024,Dallas,73991005,ENGAGE IN ORG CRIM ACT,06/20/2017,01/18/2016,17.0,Denied on 09/03/2024,09/2026,NOT IN REVIEW PROCESS
139165,Estelle,M,B,30,01/17/2026,01/17/2026,01/17/2021,Dallas,73991005,ENGAGE IN ORG CRIM ACTIVITY,07/17/2017,01/18/2016,10.0,Denied on 03/20/2025,NaN,NOT IN REVIEW PROCESS
139173,Hightower,M,B,23,04/30/2026,02/25/2027,02/25/2022,Dallas,12990002,AGG ROBBERY,03/16/2017,04/19/2016,10.0,Approved on 02/21/2025,NaN,NOT IN REVIEW PROCESS
139177,Allred,M,W,30,10/30/2051,10/30/2051,05/01/2034,Dallas,9990030,MURDER,08/18/2017,10/30/2016,35.0,NaN,05/01/2034,NOT IN REVIEW PROCESS

In [33]:
inc_df[inc_df.County == 'Austin'] # 117 observations in Austin. Why is this so low?

,Current Facility,Gender,Race,Age,Projected Release,Maximum Sentence Date,Parole Eligibility Date,County,Offense Code,TDCJ Offense,Sentence Date,Offense Date,Sentence (Years),Last Parole Decision,Next Parole Review Date,Parole Review Status
1394,Telford,M,H,68,10/20/2100,10/20/2100,10/20/2040,Austin,13150005,AGG ASLT,11/02/2011,10/21/2010,90.0,NaN,10/20/2040,NOT IN REVIEW PROCESS
1537,Jester III,M,W,69,03/24/2028,04/29/2035,08/16/2024,Austin,54040011,DWI 3RD OR MORE,07/07/2023,05/27/2020,12.0,Denied on 10/08/2024,10/2025,IN PAROLE REVIEW PROCESS
1564,Bell,M,W,69,11/06/2031,11/06/2031,02/16/2021,Austin,54040020,DWI W/PRE INTOX MANSLAUGHTER,11/08/2019,10/08/2017,12.0,Denied on 02/21/2025,02/2026,NOT IN REVIEW PROCESS
3768,Estelle,M,B,63,01/01/9999,01/01/9999,08/11/1992,Austin,9150000,MURDER,10/25/1983,03/28/1983,Life,Denied on 12/05/2024,11/2025,IN PAROLE REVIEW PROCESS
4665,Michael,M,W,64,01/01/9999,01/01/9999,11/13/2024,Austin,9150000,MURDER,05/31/1990,11/04/1989,Life,Denied on 08/30/2024,08/2029,NOT IN REVIEW PROCESS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137198,Lopez,M,B,29,10/12/2031,10/12/2031,08/04/2025,Austin,23990198,THEFT PROP $30-150K,02/18/2025,10/12/2024,7.0,NaN,Unavailable at this time.,IN PAROLE REVIEW PROCESS
137322,Michael,M,W,57,01/01/5555,01/01/5555,NaN,Austin,11990004,AGG SEXUAL ASLT CHILD U/6,06/29/2017,04/22/2015,LWOP,NaN,NaN,NaN
137334,Allred,M,W,51,07/05/2040,07/05/2040,07/05/2040,Austin,11990012,SEX ABUSE-CHILD V/U14,07/08/2015,10/11/2012,25.0,NaN,NaN,NaN
137416,Wynne,M,W,33,07/21/2032,07/21/2032,08/08/2017,Austin,22990002,BURG HABIT,10/27/2015,07/21/2015,15.0,Denied on 05/28/2024,05/2026,NOT IN REVIEW PROCESS
138500,Jester III,M,B,26,12/01/2025,12/19/2027,04/24/2025,Austin,35990248,POSS CS PG1/1-B 1-4G,03/04/2025,11/17/2021,3.0,Approved on 05/27/2025,NaN,NOT IN REVIEW PROCESS

In [2]:
# Uses my API Key and the series ID along with the requests library to obtain the data from the FRED API, turning it into a json file
API_KEY = "6854f98f39927bf9f410ddc3a8fd4c85" ## Won't hardcode in final project files
series_id = "LAUCN481130000000003A" ## Also won't hardcode in final project files

url = "https://api.stlouisfed.org/fred/series/observations"
params = {
    "series_id": series_id,
    "api_key": API_KEY,
    "file_type": "json",
    "observation_start": "2020-01-01", #Change depending on start date needed
    "observation_end": "2025-01-01"
}

resp = requests.get(url, params=params)

data = resp.json()

In [3]:
# Uses the json stored data to create a pandas dataframe of the API data
obs = data["observations"]
dallas_unemploy_df = pd.DataFrame(obs)

# Convert types for better analysis and more continuity between datasets once merged
dallas_unemploy_df["date"] = pd.to_datetime(dallas_unemploy_df["date"])
dallas_unemploy_df["value"] = pd.to_numeric(dallas_unemploy_df["value"], errors="coerce")

dallas_unemploy_df.head()

  realtime_start realtime_end       date  value
0     2025-11-19   2025-11-19 2020-01-01    7.8
1     2025-11-19   2025-11-19 2021-01-01    5.6
2     2025-11-19   2025-11-19 2022-01-01    3.8
3     2025-11-19   2025-11-19 2023-01-01    4.0
4     2025-11-19   2025-11-19 2024-01-01    4.1

In [4]:
dallas_unemploy_df['County'] = "Dallas" #Adding identifiers to the County data

In [5]:
dallas_unemploy_df

  realtime_start realtime_end       date  value  County
0     2025-11-19   2025-11-19 2020-01-01    7.8  Dallas
1     2025-11-19   2025-11-19 2021-01-01    5.6  Dallas
2     2025-11-19   2025-11-19 2022-01-01    3.8  Dallas
3     2025-11-19   2025-11-19 2023-01-01    4.0  Dallas
4     2025-11-19   2025-11-19 2024-01-01    4.1  Dallas

In [6]:
API_KEY = "6854f98f39927bf9f410ddc3a8fd4c85"
series_id = "LAUCN482010000000003A"

url = "https://api.stlouisfed.org/fred/series/observations"
params = {
    "series_id": series_id,
    "api_key": API_KEY,
    "file_type": "json",
    "observation_start": "2020-01-01",
    "observation_end": "2025-01-01"
}

resp = requests.get(url, params=params)

data = resp.json()

obs = data["observations"]
harris_unemploy_df = pd.DataFrame(obs)

# Convert types
harris_unemploy_df["date"] = pd.to_datetime(harris_unemploy_df["date"])
harris_unemploy_df["value"] = pd.to_numeric(harris_unemploy_df["value"], errors="coerce")

harris_unemploy_df.head()

  realtime_start realtime_end       date  value
0     2025-11-19   2025-11-19 2020-01-01    8.8
1     2025-11-19   2025-11-19 2021-01-01    6.3
2     2025-11-19   2025-11-19 2022-01-01    4.2
3     2025-11-19   2025-11-19 2023-01-01    4.3
4     2025-11-19   2025-11-19 2024-01-01    4.4

In [7]:
harris_unemploy_df['County'] = "Harris"

In [8]:
harris_unemploy_df

  realtime_start realtime_end       date  value  County
0     2025-11-19   2025-11-19 2020-01-01    8.8  Harris
1     2025-11-19   2025-11-19 2021-01-01    6.3  Harris
2     2025-11-19   2025-11-19 2022-01-01    4.2  Harris
3     2025-11-19   2025-11-19 2023-01-01    4.3  Harris
4     2025-11-19   2025-11-19 2024-01-01    4.4  Harris

In [9]:
merged_df = pd.merge(dallas_unemploy_df, harris_unemploy_df, how='outer')

In [10]:
merged_df

  realtime_start realtime_end       date  value  County
0     2025-11-19   2025-11-19 2020-01-01    7.8  Dallas
1     2025-11-19   2025-11-19 2020-01-01    8.8  Harris
2     2025-11-19   2025-11-19 2021-01-01    5.6  Dallas
3     2025-11-19   2025-11-19 2021-01-01    6.3  Harris
4     2025-11-19   2025-11-19 2022-01-01    3.8  Dallas
5     2025-11-19   2025-11-19 2022-01-01    4.2  Harris
6     2025-11-19   2025-11-19 2023-01-01    4.0  Dallas
7     2025-11-19   2025-11-19 2023-01-01    4.3  Harris
8     2025-11-19   2025-11-19 2024-01-01    4.1  Dallas
9     2025-11-19   2025-11-19 2024-01-01    4.4  Harris

In [15]:
merged_df = merged_df.drop('realtime_start', axis = 1)

In [16]:
merged_df = merged_df.drop('realtime_end', axis = 1)

In [17]:
merged_df

        date  value  County
0 2020-01-01    7.8  Dallas
1 2020-01-01    8.8  Harris
2 2021-01-01    5.6  Dallas
3 2021-01-01    6.3  Harris
4 2022-01-01    3.8  Dallas
5 2022-01-01    4.2  Harris
6 2023-01-01    4.0  Dallas
7 2023-01-01    4.3  Harris
8 2024-01-01    4.1  Dallas
9 2024-01-01    4.4  Harris